import os
import asyncio
import tempfile
import aiofiles
import pycountry

from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from telegraph import Telegraph
from pymediainfo import MediaInfo


# =========================================
# 🔹 Telegraph init (safe)
# =========================================
telegraph = Telegraph()
telegraph.create_account(short_name="FileInfoBot")


# =========================================
# 🔹 Language full name + native name
# Bengali → Bengali (বাংলা)
# =========================================
def get_lang_name(code: str | None) -> str:
    if not code:
        return "Unknown"

    code = str(code).lower().strip()

    try:
        lang = (
            pycountry.languages.get(alpha_2=code)
            or pycountry.languages.get(alpha_3=code)
        )

        if lang:
            name = lang.name
            native = getattr(lang, "native", None)

            if native and native != name:
                return f"{name} ({native})"

            return name
    except:
        pass

    return code.upper()


# =========================================
# 🔹 CALLBACK
# =========================================
@Client.on_callback_query(filters.regex("^trackinfo$"))
async def telegraph_file_info(client, query):

    await query.answer("🔍 Scanning file...")

    tmp = os.path.join(tempfile.gettempdir(), f"info_{query.id}.tmp")

    try:
        # ======================================
        # 🔥 STREAM ONLY 3-5MB (ULTRA SAFE)
        # ======================================
        async with aiofiles.open(tmp, "wb") as f:
            async for chunk in client.stream_media(query.message, limit=4):
                await f.write(chunk)

        media = await asyncio.to_thread(MediaInfo.parse, tmp)

        video_info = []
        audios = []
        subs = []

        seen_audio = set()
        seen_subs = set()

        # ======================================
        # 🔥 Extract tracks
        # ======================================
        for t in media.tracks:

            ttype = (t.track_type or "").lower()

            # ---------- VIDEO ----------
            if ttype == "video":
                codec = t.format or "Unknown"
                w = t.width or "?"
                h = t.height or "?"
                video_info.append(f"{codec} • {w}x{h}")

            # ---------- AUDIO ----------
            elif ttype == "audio":

                lang = get_lang_name(t.language)
                key = (lang, t.title)

                if key not in seen_audio:
                    seen_audio.add(key)

                    label = lang

                    if getattr(t, "default", "") == "Yes":
                        label += " ⭐ Default"

                    audios.append(label)

            # ---------- SUBTITLE ----------
            elif ttype in ("text", "subtitle"):

                lang = get_lang_name(t.language)
                key = (lang, t.title)

                if key not in seen_subs:
                    seen_subs.add(key)

                    label = lang

                    if getattr(t, "forced", "") == "Yes":
                        label += " 🎯 Forced"

                    subs.append(label)

        # ======================================
        # 🔥 Beautiful HTML UI
        # ======================================
        html = """
        <h2>📊 File Tracks Info</h2>
        <hr>
        """

        # VIDEO
        if video_info:
            html += "<b>📺 Video</b><br>"
            for v in video_info:
                html += f"• {v}<br>"
            html += "<br>"

        # AUDIO
        html += f"<b>🔊 Audio Tracks ({len(audios)})</b><br>"
        if audios:
            for a in audios:
                html += f"• {a}<br>"
        else:
            html += "None<br>"
        html += "<br>"

        # SUBTITLE
        html += f"<b>💬 Subtitle Tracks ({len(subs)})</b><br>"
        if subs:
            for s in subs:
                html += f"• {s}<br>"
        else:
            html += "None<br>"

        html += """
        <br><hr>
        <i>Generated by your bot ⚡</i>
        """

        # ======================================
        # 🔥 Telegraph page create
        # ======================================
        page = await asyncio.to_thread(
            telegraph.create_page,
            title="File Info",
            html_content=html
        )

        # ======================================
        # 🔥 Replace button with link
        # ======================================
        await query.edit_message_reply_markup(
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("📊 View File Info", url=page["url"])]
            ])
        )

    except Exception:
        await query.answer("❌ Failed to read info", show_alert=True)

    finally:
        if os.path.exists(tmp):
            os.remove(tmp)
